### PR TITLE
fix for column visualization when row data is not present

### LINKED ISSUE #37: HTML Output shows Data column(s) for axis #0 cannot be of type string in google visualization when there is no rows but the column is present
The output of the following command will yield in no data for some of the boards which is not handled by google visualizations. 

go run pullsheet.go leaderboard --repos google/pullsheet --since 2021-05-06 --token-path gh_token.txt > test.html

The visualization in browser gives the error Data column(s) for axis #0 cannot be of type string

Line 102 in test.html should look like this `[{label:'',type:'string'},{label: '# of Merged PRs reviewed', type: 'number'}, { role: 'annotation' }],`
but curretnly looks like this `['', '# of Merged PRs reviewed', { role: 'annotation' }],`

### PR DESCRIPTION
**Pull request by vigothehacker**
fixes #37

### CODE REVIEW

**Review by medyagh — COMMENTED** [review]
@vigothehacker to help reviewing this PR do u mind pasting the before/after this PR  screenshot please ?

**Comment by vigothehacker** [comment]
Before
image


After
image

**Comment by MarlonGamez** [comment]
lgtm, did some testing locally and seems to work well. Thanks @vigothehacker :) And sorry for the large delay

**Review by MarlonGamez — APPROVED** [review]

**Pull request merged**
